//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCeza
    {
        public int Id { get; set; }
        public Nullable<int> Uye { get; set; }
        public Nullable<int> Hareket { get; set; }
        public Nullable<decimal> Para { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual tblHareket tblHareket { get; set; }
        public virtual tblUyeler tblUyeler { get; set; }
    }
}
